term.clear()
term.setCursorPos(1,1)
print("")
print("")
print("")
print("")
print("               +----+------->XXX                  ")
print("               |    |        XXX                  ")
print("               |  +------------+XXX               ")
print("               +----+          |XXX               ")
print("               |  |  BCWorks   | ||               ")
print("               |  |    MiniOS  | \\/               ")
print("               |  |          +----+               ")
print("               |  +------------+  |               ")
print("               |             |    |               ")
print("               +-------------+----+               ")
os.sleep(5)
term.clear()
term.setCursorPos(1,1)
local mainModule = require("/BCWorks_MiniOS/main.lua")
mainModule.main()